services:
  spark-master:
    image: spark-image
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: ${SPARK_HOME}/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_LOCAL_IP=spark-master
    volumes:
      - ${HOME}/docker/volumes/spark/data:${SPARK_HOME}/data
    networks:
      - spark-network

  spark-worker-1:
    image: spark-image
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: ${SPARK_HOME}/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
      - ${HOME}/docker/volumes/spark/data:${SPARK_HOME}/data
    networks:
      - spark-network

  spark-worker-2:
    image: spark-image
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    command: ${SPARK_HOME}/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
      - ${HOME}/docker/volumes/spark/data:${SPARK_HOME}/data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge