services:
  manager:
    container_name: hadoop-manager
    image: hadoop-image:latest
    hostname: manager
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash /start-hadoop.sh"]
    ports:
      - "30000:9870"  # HDFS NameNode Web UI
      - "40000:8088"  # YARN ResourceManager Web UI
      - "35000:19888" # MapReduce Job History Server Web UI
    volumes:
      - ${HOME}/docker/volumes/hadoop/data/manager:${HADOOP_DATA}
    environment:
      - HADOOP_YARN_ROLE=resourcemanager
      - HADOOP_HDFS_ROLE=namenode
    networks:
      - hadoop-network
    restart: unless-stopped
  worker1:
    container_name: hadoop-worker1
    image: hadoop-image:latest
    hostname: worker1
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash /start-hadoop.sh"]
    ports:
      - "30001:9864"  # DataNode Web UI
      - "40001:8042"  # NodeManager Web UI
    volumes:
      - ${HOME}/docker/volumes/hadoop/data/worker1:${HADOOP_DATA}
    environment:
      - HADOOP_YARN_ROLE=nodemanager
      - HADOOP_HDFS_ROLE=datanode
    networks:
      - hadoop-network
    restart: unless-stopped
  worker2:
    container_name: hadoop-worker2
    image: hadoop-image:latest
    hostname: worker2
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash /start-hadoop.sh"]
    ports:
      - "30002:9864"  # DataNode Web UI
      - "40002:8042"  # NodeManager Web UI
    volumes:
      - ${HOME}/docker/volumes/hadoop/data/worker2:${HADOOP_DATA}
    environment:
      - HADOOP_YARN_ROLE=nodemanager
      - HADOOP_HDFS_ROLE=datanode
    networks:
      - hadoop-network
    restart: unless-stopped
  worker3:
    container_name: hadoop-worker3
    image: hadoop-image:latest
    hostname: worker3
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash /start-hadoop.sh"]
    ports:
      - "30003:9864"  # DataNode Web UI
      - "40003:8042"  # NodeManager Web UI
    volumes:
      - ${HOME}/docker/volumes/hadoop/data/worker3:${HADOOP_DATA}
    environment:
      - HADOOP_YARN_ROLE=nodemanager
      - HADOOP_HDFS_ROLE=datanode
    networks:
      - hadoop-network
    restart: unless-stopped

networks:
  hadoop-network:
    driver: bridge
    name: hadoop-network